server:
  port: 8102
spring:
  application:
    name: cloudnet-service
  cloud:
    loadbalancer:
      retry:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #如果从前一次发送心跳时间起，90秒没接受到新的心跳，讲剔除服务
    lease-expiration-duration-in-seconds: 90
    #30s发送一次心跳 到注册中心,不配置默认也是30s
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8001/eureka/

